name: Auth Service CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]	

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Télécharger le code
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        python -m venv venv	
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lancer les tests
      run: |
        source venv/bin/activate
        if ! python manage.py test; then
           echo "Les tests ont échoué"
          exit 1
        fi
